### ISSUE TITLE
Contributionガイドの作成について

### ISSUE THREAD

**Issue by PoohSunny** [koji-k/groovy-tutorial#2]
適宜コントリビュートしていきたいな、と思っているのでコントリビューションガイドがあると助かります。

**Comment by koji-k** [comment]
ありがとうございます。非常に助かります！
特に何も考えずに一人で作成してきたので、一旦コントリビューションガイドの作成と共にどうやって管理していくのか、を纏めます。
Markdownでリポジトリにあげるので、その時点で再度お知らせ&このISSUEをcloseします。

**Comment by koji-k** [comment]
コントリビューションガイドを作成しました！
https://github.com/koji-k/groovy-tutorial/blob/master/CONTRIBUTING.md
README.mdと合わせてご確認いただければと思います。

**Comment by PoohSunny** [comment]
確認しました！　丁寧にありがとうございました！！
